apiVersion: v1
kind: Service
metadata:
  name: roboshop-Service
  labels:
    purpose: service-demo
selector:
  env: test
  project: roboshop  
  


---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels: 
    env: test
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx


