#service

apiVersion: v1
kind: Service
metadata:
  name: node-port-demo
  labels:
    purpose: nodeport-svc-demo

spec:
  type: NodePort
  selector:
      env: test
      project: roboshop
      purpose: testing

  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
    project: roboshop
    purpose: testing

spec:
  containers:
    - name: nginx
      image: nginx
  

