# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: replica-pod

# spec:
#   replicas: 3 # how many pods. you want define here
#   selector:
#     matchLabels:
#       env: test
#       purpose: replica-demo
#       project: roboshop
# #this pod defination
#   template:
#     metadata:
#       labels:
#         env: test
#         purpose: replica-demo
#         project: roboshop
#     spec:
#       containers:
#         - name: nginx
#           image: nginx


#creating replica set

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaPod

spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: replicademo
      env: test
      component: frontend

# pod defination
  template:
    metadata:
      labels:
        purpose: replicademo
        env: test
        component: frontend
  spec:
    containers:
    - name: nginx
      image: nginx:1.24