apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    # pod labels
    purpose: service-lb-demo
    tier: app
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # serviec port
      targetPort: 80  # container port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
    tier: app
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
