pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                echo 'This is the 1st stage'
            }
        }

        stage('Configure') {
            steps {
                echo 'All is well'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing is good'
            }
        }
    }

    post {

        always {
            echo 'Pipeline execution completed. Check the status below.'
        }

        success {
            echo 'Pipeline was successful.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}