pipeline {

agent any

stages {

    stage('Build') {
        steps {
            echo 'Welcome back guru...!'
        }
    }

    stage('Deploy') {
        steps {
            echo 'Now deploying..!'
        }
    }

}


}
