pipeline {

    agent {
        label 'AGENT-1'
    }

    environment {
        course = 'Jenkins'
    }

    stages {

        stage('Build') {
            steps {
                script {
                    sh """
                        echo "Hello brother"
                        env
                    """
                }
            }
        }

        stage('Configure') {
            steps {
                echo 'All is well'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing is good'
            }
        }
    }

    post {

        always {
            echo 'Pipeline execution completed. Check the status below.'
        }

        success {
            echo 'Pipeline was successful.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}