- name: installation of catalogue server
  hosts: catalogue
  become: yes
  tasks:
  
  - name: disabling default nodejs module
    ansible.builtin.command: dnf module disable nodejs

  - name: enable nodejs 20 module
    ansible.builtin.command: dnf module enable nodejs:20

  - name: installing the nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: create a system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create a directory 
    ansible.builtin.file: 
      path: /app
      state: directory
 
  - name: download the catalogue url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
      
  - name: extract catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: node modules installation
    community.general.npm:
      path: /app

  - name: copying the service conifguration
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: configuring catalogue service
    ansible.builtin.systemd:
      name: catalogue
      daemon_reload: true

  - name: start and enable service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0


  

